# 业务配置写这里

#示例配置
demo-yaml-config:
  #对应单个值
  value: 345
  #对应数组
  valueArray: 1,2,3,4,5,6,7,8,9
  #对应list
  valueList:
    - 13579
    - 246810
  # 对应map
  valueMap:
    name: lili
    age: 20
    sex: female
    #对应list<map>
  valueMapList:
    - name: bob
      age: 21
    - name: caven
      age: 31
  #      统计任务的cron表达式
  statsticsCron: 0 * * * * ?